SEND PAPDEV:UTIL:TNT:PALS

BATCH REQUEST #26653 HAS BEEN COMPLETED.

FROM SYSTEM 26 TO SYSTEM 34.

(TNT)BASE1.DMS THRU BASE3.DMS, BASE6.DMS, CALBAK.DMS, STATBK.DMS,
TNUM.DMS AND NPAP.DMS.

(TNT)PAPER.SAV WAS RESTORED AS PAPER.RUN.

FREMONT OPERATIONS - R.E.

GFD
SYS.ME
DA
