        SUBROUTINE CHHN1(BASX,TNUM,ME,STAT,UNAM)
C
C       CHANGE THE CONTROL GROUP
C
        INTEGER HN,NHN,TNUM,NUMBER,Z,IERT,IERC,IBF
        INTEGER MIDV(4),NT,ME,STAT,UNAM(3),ORDER,SDAT
        INTEGER BAS,BASX,TIM1,INFO(64)
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC
        INTEGER NUMCG,NETOP
	COMMON /NUMCG/NUMCG/NETOP/NETOP(35)

	BAS=BASX
90      Z=1
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 110,TNUM
110     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL('HN',HN)
116     TYPE 115,TNUM,NETOP(HN)
115     FORMAT(/1X,'THE CURRENT CONTROL GROUP FOR TICKET NUMBER ',I8,
     1  ' IS... ',//5X,A5,/)
	TYPE 117,(I,NETOP(I),I=1,NUMCG)
117	FORMAT(5(4X,I2,' = ',A5))
	TYPE 118
118	FORMAT(1X,'ENTER THE NEW VALUE OR A C.R. FOR NO CHANGE : ',$)
        ACCEPT 120,NHN
        IF (NHN.GT.27) GOTO 116
120     FORMAT(I2)
        IF (NHN.EQ.0) GOTO 300
	CALL CHA1I(BAS,53,NHN,TNUM)
	CALL GETC(6,UNAM,PCE)
	IF(PCE.EQ."040) GOTO 401
	CALL GETC(11,UNAM,PCE)
	IF(PCE.EQ."040) GOTO 403
C	IF(UNAM(2).EQ.'     ') GOTO 401
C	IF(UNAM(3).EQ.'     ') GOTO 403
        ENCODE(90,400,INFO)UNAM,ME,NETOP(HN),NETOP(NHN)
400     FORMAT(3A5,1H(,A3,1H),' CHANGED THE CONTROL GROUP FROM ',A5,
     1  ' TO ',A5,14X,'.',5X)
        GOTO 405

401     ENCODE(90,402,INFO)UNAM(1),ME,NETOP(HN),NETOP(NHN)
402     FORMAT(A5,1H(,A3,1H),' CHANGED THE CONTROL GROUP FROM ',A5,
     1  ' TO ',A5,24X,'.',5X)
        GOTO 405

403     ENCODE(90,404,INFO)UNAM(1),UNAM(2),ME,NETOP(HN),NETOP(NHN)
404     FORMAT(A5,A5,1H(,A3,1H),' CHANGED THE CONTROL GROUP FROM ',A5,
     1  ' TO ',A5,19X,'.',5X)
405     CALL RTIM(TIM1,SDAT)
	CALL OPENDB(2,$297,1)
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        ORDER=NUMBER+1
        CALL DBADD(1,TNUM,2,SDAT,3,TIM1,4,ME,5,5,6,STAT,7,INFO,8,UNAM,
     1  9,ORDER,10,0)
        CALL DBCLOS
        ENCODE(95,416,INFO)
416     FORMAT(95(1H ))
        ENCODE(5,420,OHN)HN
420     FORMAT(2X,I1,2X)
	CALL OPENDB(3,$297,1)
        CALL DBADD(1,TNUM,2,SDAT,3,TIM1,4,ME,5,'HNCHG',6,NHN,7,OHN,
     1  8,UNAM)
        CALL DBCLOS
	CALL OPENDB(16,$295,1)
        CALL DBFIND(2,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.LT.1) GOTO 233
        CALL DBCHNG(7,NHN)
233     CALL DBCLOS
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. PLEASE TRY',
     1  ' AGAIN.')
	BAS=1
        GOTO 90

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

297     TYPE 298,IERT,IERC
298     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'AUTO-STAT REGARDING CONTROL GROUP CHANGE WAS NOT ',
     2  'COMPLETED NORMALLY.')
        RETURN

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE CHDUP1(BASX)
C
C	CHANGE THE DUP NUMBER
C
        INTEGER BAS,BASX,DUP,DAT,TNUM,NUMBER,Z,IBF,IERT,IERC,ELM
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

	BAS=BASX
90      Z=1
        ELM=0
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 110,TNUM
110     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL('DUP',DUP)
        CALL DBNDAT(DUP,SM,SD,SY)
        TYPE 115,TNUM,SM,SD,SY
115     FORMAT(/1X,'THE CURRENT DATE UP FOR TICKET NUMBER ',I8,
     1  ' IS... ',/,/5X,I2,1H-,I2,1H-,I4,/,/1X,'ENTER THE NEW VALUE ',
     2  'OR A C.R. FOR NO CHANGE : ')
        CALL CGDAT(DAT)
120     FORMAT(I6)
        IF (DAT.EQ.0) GOTO 300
        CALL CHA1I(BAS,49,DAT,TNUM)
        CALL CHA1I(BAS,54,ELM,TNUM)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. PLEASE TRY',
     1  ' AGAIN.')
	BAS=1
        GOTO 90

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE INPTIM(NTIM)
C
C       GET THE TIME INPUT
C
        INTEGER A1,A2,A3,A4,A5,NTIM,TUP

100     TYPE 105
105     FORMAT(1X'ENTER THE TIME HH:MM  ? ',$)
        ACCEPT 110,NTIM
110     FORMAT(A5)
        IF (NTIM.EQ.'     ') RETURN
        DECODE(5,115,NTIM)A1,A2,A3,A4,A5
115     FORMAT(A1,A1,A1,A1,A1)
        IF (A3.NE.':') GOTO 100
        IF ((A1.LT.'0').OR.(A1.GT.'2')) GOTO 100
        IF ((A2.LT.'0').OR.(A2.GT.'9')) GOTO 100
        IF ((A4.LT.'0').OR.(A4.GT.'5')) GOTO 100
        IF ((A5.LT.'0').OR.(A4.GT.'9')) GOTO 100
        RETURN

        END
        SUBROUTINE CHTDWN
C
C       CHANGE THE TIME NUMBER
C
        INTEGER BAS,TIME,NTIME,TNUM,NUMBER,Z,IERT,IERC,DAT,ELM,NTIM,IBF
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

90      BAS=1
        Z=1
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 110,TNUM
110     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL('TIME',TIME)
        TYPE 115,TNUM,TIME
115     FORMAT(/1X,'THE CURRENT TIME DOWN FOR TICKET NUMBER ',I8,
     1  ' IS... ',/,/5X,A5,/,/1X,'ENTER THE NEW VALUE ',
     2  'OR A C.R. FOR NO CHANGE : ')
        CALL INPTIM(NTIM)
120     FORMAT(I6)
        IF (NTIM.EQ.0) GOTO 300
125     CALL DBERR($130,IERT,IERC,IBF)
        GOTO 135

130     IF (IERT.NE.7) GOTO 295
        TYPE 132
132     FORMAT(1X,'DATA BASE BUSY... WAITING 10 SECS.')
        CALL WAIT(8.0)
135     CALL DBOPEN(BASE(1,BAS))
        CALL DBUPD(-1)
        CALL DBFIND(1,1,TNUM)
        CALL DBCHNG('TIME',NTIM,'ELM',0)
        CALL DBCLOS
        TYPE 140
140     FORMAT(3X'CHANGE IS COMPLETE',/)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. PLEASE TRY',
     1  ' AGAIN.')
        GOTO 90

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE CHTUP1
C
C       CHANGE THE TUP NUMBER
C
        INTEGER BAS,TUP,NTUP,TNUM,NUMBER,Z,IERT,IERC,DAT,ELM,NTIM,IBF
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

90      BAS=1
        Z=1
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 110,TNUM
110     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL('TUP',TUP)
        TYPE 115,TNUM,TUP
115     FORMAT(/1X,'THE CURRENT TIME UP FOR TICKET NUMBER ',I8,
     1  ' IS... ',/,/5X,A5,/,/1X,'ENTER THE NEW VALUE ',
     2  'OR A C.R. FOR NO CHANGE : ')
        CALL INPTIM(NTIM)
120     FORMAT(I6)
        IF (NTIM.EQ.0) GOTO 300
125	CALL OPENDB(BAS,$295,1)
        CALL DBFIND(1,1,TNUM)
        CALL DBCHNG('TUP',NTIM,'ELM',0)
        CALL DBCLOS
        TYPE 140
140     FORMAT(3X'CHANGE IS COMPLETE',/)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. PLEASE TRY',
     1  ' AGAIN.')
        GOTO 90

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN
300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE DRP1(UNAM,INT,VERS)
C
C       DROP A TICKET FROM ALL THE BASES
C
        INTEGER HOST,NHOST,TNUM,NUMBER,Z,IERT,IERC,IBF
        INTEGER BAS,UNAM(3),ANS,INT,TIM1,SDAT,VERS
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

	IF (UNAM(1).EQ.'NETCO') RETURN
90      BAS=1
        Z=1
100     TYPE 105
105     FORMAT(1X,'ENTER THE TICKET NUMBER TO BE DELETED: ',$)
        ACCEPT 110,TNUM
110     FORMAT(I6)
        IF (TNUM.EQ.0) RETURN
        CALL RTIM(TIM1,SDAT)
        CALL DBOPEN(BASE(1,3))
        CALL DBADD(1,TNUM,2,SDAT,3,TIM1,4,INT,5,'DELET',8,UNAM)
        CALL DBCLOS
125	CALL OPENDB(BAS,$295,1)
        TYPE 136,TNUM,BASE(1,BAS),BASE(2,BAS)
136     FORMAT(1X,'CHECK FOR TICKET # ',I6,' IN FILE ',2A10)
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF ((NUMBER.EQ.0).AND.(Z.EQ.1)) GOTO 400
        IF (NUMBER.EQ.0) GOTO 138
        TYPE 137,NUMBER,BASE(1,BAS),BASE(2,BAS)
137     FORMAT(1X,'DELETED  ',I3,' RECORD(S) FROM ',2A10)
        CALL DBDEL
138     CALL DBCLOS
        Z=Z+1
        IF (Z.EQ.2) BAS=2
        IF (Z.EQ.3) BAS=6
        IF (Z.EQ.4) BAS=8
        IF (Z.EQ.5) RETURN
        GOTO 125

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

400     CALL DBCLOS
        CALL DEOLD(TNUM)
        RETURN

        END
        SUBROUTINE DEOLD(TNUM)
C
C       DROP A TICKET FROM ALL THE BASES
C
        INTEGER BAS,HOST,NHOST,TNUM,NUMBER,Z,IERT,IERC,IBF
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

90      BAS=4
        Z=1
125	CALL OPENDB(BAS,$295,1)
        TYPE 136,TNUM,BASE(1,BAS),BASE(2,BAS)
136     FORMAT(1X,'CHECK FOR TICKET # ',I8,' IN FILE ',2A10)
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 138
        TYPE 137,NUMBER,BASE(1,BAS),BASE(2,BAS)
137     FORMAT(1X,'DELETED  ',I3,' RECORD(S) FROM ',2A10)
        CALL DBDEL
138     CALL DBCLOS
        Z=Z+1
        IF (Z.EQ.2) BAS=5
        IF (Z.EQ.3) BAS=7
        IF (Z.EQ.4) BAS=9
        IF (Z.EQ.5) RETURN
        GOTO 125

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

        END
        SUBROUTINE CHA1I(BAS,ATB,VALU,TNUM)
C
C       CHANGE A NUMBER IN THE TROUBLE TICKET
C
        INTEGER BAS,ATB,VALU,TNUM,IERT,IERC,IBF
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)/IBF/IBF,IERT,IERC

        TYPE 122,BASE(1,BAS),BASE(2,BAS)
122     FORMAT(1X,'OPENING ',2A10,' FOR UPDATE ',$)
125	CALL OPENDB(BAS,$295,1)
        CALL DBFIND(1,1,TNUM)
        CALL DBCHNG(ATB,VALU)
        CALL DBCLOS
        TYPE 140
140     FORMAT('+','...CHANGE IS COMPLETE')
        RETURN

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

        END
        SUBROUTINE CHA4A5(BASX,BAST,ATB1,ATB2,OUT)
C
C       CHANGE AN ATTRIBUTE OF A 4A5 SIZE
C
        INTEGER CKT(4),NCKT(4),TNUM,NUMBER,Z,IERT,IERC,IBF
        INTEGER MIDV(4),NT,ATB1,ATB2,OUT(2)
        INTEGER BAS,BASX,BAST,FLD,FL1
	COMMON /FLD/FLD(3),FL1(3)
	DOUBLE PRECISION BASE,NET
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

	BAS=BASX
90      Z=1
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 113,TNUM
113     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL(ATB1,CKT,48,NT,9,NET)
        IF (NT.EQ.1) CALL DBVAL(40,MIDV(1))
        IF (NT.EQ.2) CALL DBVAL(42,MIDV(1))
        IF (NT.EQ.3) CALL DBVAL(43,MIDV)
        TYPE 112,TNUM,OUT,CKT
112     FORMAT(/1X,'TICKET NUMBER : ',I8,3X,2A5,' EQUALS : ',4A5,
     1  /,/1X,'ENTER THE NEW VALUE OR A C.R. FOR NO CHANGE : ',$)
        ACCEPT 120,NCKT
120     FORMAT(4A5)
	CALL UPCASE(NCKT)
        IF (NCKT(1).EQ.'     ') GOTO 300

        TYPE 122,BASE(1,BAS),BASE(2,BAS)
122     FORMAT(1X,'OPENING ',2A10,' FOR UPDATE ',$)
125	CALL OPENDB(BAS,$295,1)
        CALL DBFIND(1,1,TNUM)
        CALL DBCHNG(ATB1,NCKT)
        CALL DBCLOS
        TYPE 140
140     FORMAT('+','...CHANGE IS COMPLETE')
        IF (ATB2.EQ.0) RETURN

	TYPE 117,BASE(1,BAST),BASE(2,BAST)
117     FORMAT(1X,'OPENING ',2A10,' FOR UPDATE',$)
	CALL OPENDB(BAST,$295,1)
	IF(NT.EQ.3)CALL DBFIND(17,1,FLD(NT),1,FL1(NT),1,MIDV,1,3,1,NET)
        IF((NT.EQ.1).OR.(NT.EQ.2))CALL DBFIND(17,1,FLD(NT),1,
     1  FL1(NT),1,MIDV(1),1,3,1,NET)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 280
        CALL DBCHNG(ATB2,NCKT)
        CALL DBCLOS
        TYPE 121
121     FORMAT('+','... CHANGE IS COMPLETE')
        RETURN

280     TYPE 285
285     FORMAT(3X,'NO RELATION RECORD EXISTS...',/)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. TRY AGAIN',
     1  ' PLEASE.')
	BAS=1
        GOTO 90

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE CH1I(BASX,BAST,ATB1,ATB2,OUT)
C
C       CHANGE AN ATTRIBUTE OF A NUMBER FIELD
C
        INTEGER CKT,NCKT,TNUM,NUMBER,Z,IERT,IERC,IBF
        INTEGER MIDV(4),NT,ATB1,ATB2,OUT(2)
        REAL ELM
        INTEGER BAS,BASX,BAST,FLD,FL1
	COMMON /FLD/FLD(3),FL1(3)
	DOUBLE PRECISION BASE,NET
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

	BAS=BASX
90      Z=1
100     TYPE 101
101     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 102,TNUM
102	FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
104	CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        IF(ATB1.NE.54) CALL DBVAL(ATB1,CKT,48,NT,9,NET)
        IF(ATB1.EQ.54) CALL DBVAL(ATB1,ELM,48,NT,9,NET)
        IF (NT.EQ.1) CALL DBVAL(40,MIDV(1))
        IF (NT.EQ.2) CALL DBVAL(42,MIDV(1))
        IF (NT.EQ.3) CALL DBVAL(43,MIDV)
        IF(ATB1.EQ.54) GOTO 106
        TYPE 105,TNUM,OUT,CKT
105     FORMAT(/1X,'TICKET NUMBER : ',I8,3X,2A5,' EQUALS : ',I8,
     1  /,/1X,'ENTER THE NEW VALUE OR A C.R. FOR NO CHANGE : ',$)
	GOTO 108

106	TYPE 107,TNUM,OUT,ELM
107	FORMAT(/1X,'TICKET NUMBER : ',I8,3X,2A5,' EQUALS : ',F8.1,
     1 /,/1X,'ENTER THE NEW VALUE OR A C.R. FOR NO CHANGE : ',$)
108	ACCEPT 109,NCKT
109     FORMAT(I8)
        IF (NCKT.EQ.0) GOTO 300
        IF(ATB1.EQ.54) ELM=NCKT
	TYPE 110,BASE(1,BAS),BASE(2,BAS)
110     FORMAT(1X,'OPENING ',2A10,' FOR UPDATE ',$)
125	CALL OPENDB(BAS,$295,1)
        CALL DBFIND(1,1,TNUM)
        IF(ATB1.NE.54) CALL DBCHNG(ATB1,NCKT)
        IF(ATB1.EQ.54) CALL DBCHNG(ATB1,ELM)
        CALL DBCLOS
        TYPE 140
140     FORMAT('+','...CHANGE IS COMPLETE')
        IF (ATB2.EQ.0) RETURN

	TYPE 117,BASE(1,BAST),BASE(2,BAST)
117     FORMAT(1X,'OPENING ',2A10,' FOR UPDATE',$)
	CALL OPENDB(BAST,$295,1)
        IF (NT.EQ.3) CALL DBFIND(17,1,FLD(NT),1,FL1(NT),1,MIDV,1,3,
     1  1,NET)
        IF((NT.EQ.1).OR.(NT.EQ.2))CALL DBFIND(17,1,FLD(NT),1,
     1  FL1(NT),1,MIDV(1),1,3,1,NET)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 280
        CALL DBCHNG(ATB2,NCKT)
        CALL DBCLOS
        TYPE 121
121     FORMAT('+','... CHANGE IS COMPLETE')
        RETURN

280     TYPE 285
285     FORMAT(3X,'NO RELATION RECORD EXISTS...',/)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 104

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. TRY AGAIN',
     1  ' PLEASE.')
	BAS=1
        GOTO 90

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE CHASTH(BASX,BAST)
C
C       CHANGE THE START HOUR
C
        INTEGER SLOT,NSLOT,TNUM,NUMBER,Z,IBF,IERT,IERC
        INTEGER BAS,BASX,BAST,MIDV(4),NT
	DOUBLE PRECISION BASE,NET
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

	BAS=BASX
90      Z=1
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 110,TNUM
110     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL('STH',SLOT,48,NT,9,NET)
        IF (NT.EQ.1) CALL DBVAL(40,MIDV(1))
        IF (NT.EQ.2) CALL DBVAL(42,MIDV(1))
        IF (NT.EQ.3) CALL DBVAL(43,MIDV)
        TYPE 115,TNUM,SLOT
115     FORMAT(/1X,'THE CURRENT START HOUR(GMT) FOR TICKET NUMBER ',I8,
     1  ' IS... ',/,/5X,A5,/,/1X,'ENTER THE NEW VALUE OR A C.R. FOR ',
     2  'NO CHANGE.')
        CALL INPTIM(NSLOT)
120     FORMAT(A5)
        IF (NSLOT.EQ.0) GOTO 300
        CALL CHA1A(BAS,28,NSLOT,TNUM)
        CALL CHRE1A(BAST,NT,MIDV,14,NSLOT,NET)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. PLEASE TRY',
     1  ' AGAIN.')
	BAS=1
        GOTO 90

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE CHAEHR(BAST)
C
C       CHANGE THE END HOUR
C
        INTEGER SLOT,NSLOT,TNUM,NUMBER,Z,IBF,IERT,IERC
        INTEGER BAS,BASX,BAST,MIDV(4),NT
	DOUBLE PRECISION BASE,NET
	COMMON /BASE/BASE(2,20)
	COMMON /IBF/IBF,IERT,IERC

	BAS=BASX
90      Z=1
100     TYPE 105
105     FORMAT(1X,'TICKET NUMBER : ',$)
        ACCEPT 110,TNUM
110     FORMAT(I8)
        IF (TNUM.EQ.0) RETURN
114     CALL DBOPEN(BASE(1,BAS))
        CALL DBFIND(1,1,TNUM)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 200
        CALL DBGREC($300,NUMBER)
        CALL DBVAL('EHR',SLOT,48,NT,9,NET)
        IF (NT.EQ.1) CALL DBVAL(40,MIDV(1))
        IF (NT.EQ.2) CALL DBVAL(42,MIDV(1))
        IF (NT.EQ.3) CALL DBVAL(43,MIDV)
        TYPE 115,TNUM,SLOT
115     FORMAT(/1X,'THE CURRENT END HOUR(GMT) FOR TICKET NUMBER ',I8,
     1  ' IS... ',/,/5X,A5,/,/1X,'ENTER THE NEW VALUE OR A C.R. FOR ',
     2  'NO CHANGE.')
        CALL INPTIM(NSLOT)
120     FORMAT(A5)
        IF (NSLOT.EQ.0) GOTO 300
        CALL CHA1A(BAS,29,NSLOT,TNUM)
        CALL CHRE1A(BAST,NT,MIDV,15,NSLOT,NET)
        RETURN

200     IF (Z.EQ.2) GOTO 215
        Z=2
	BAS=4
        GOTO 114

215     TYPE 220,TNUM
220     FORMAT(1X,'TICKET NUMBER ',I8,' CAN NOT BE FOUND. PLEASE TRY',
     1  ' AGAIN.')
	BAS=1
        GOTO 90

300     TYPE 305
305     FORMAT(1X,'NO CHANGE WAS MADE.')
        CALL DBCLOS
        RETURN

        END
        SUBROUTINE CHA1A(BAS,ATB,VALU,TNUM)
C
C       CHANGE A 1A5 FIELD
C
        INTEGER BAS,ATB,VALU,TNUM,IERT,IERC,IBF
	DOUBLE PRECISION BASE
	COMMON /BASE/BASE(2,20)/IBF/IBF,IERT,IERC

        TYPE 122,BASE(1,BAS),BASE(2,BAS)
122     FORMAT(1X,'OPENING ',2A10,' FOR UPDATE ',$)
125	CALL OPENDB(BAS,$295,1)
        CALL DBFIND(1,1,TNUM)
        CALL DBCHNG(ATB,VALU)
        CALL DBCLOS
        TYPE 140
140     FORMAT('+','...CHANGE IS COMPLETE')
        RETURN

295     TYPE 296,IERT,IERC
296     FORMAT(/3X,'ERROR TYPE = ',I5,4X,'ERROR CODE = ',I5,
     1  /,/2X,'CHANGE IS NOT COMPLETE.')
        RETURN

        END
        SUBROUTINE CHRE1A(BAS,NT,CKT,ATB,VALU,NET)
C
C       CHANGE THE RELATIONAL DATABASE
C
        INTEGER NT,CKT(4),BAS,ATB,VALU,NUMBER
        INTEGER FLD,FL1,IERT,IERC,IBF
	COMMON /FLD/FLD(3),FL1(3)
	DOUBLE PRECISION BASE,NET
	COMMON /BASE/BASE(2,20)/IBF/IBF,IERT,IERC

	TYPE 100,BASE(1,BAS),BASE(2,BAS)
100	FORMAT(1X,'OPENING ',2A10,' FOR UPDATE',$)

	CALL OPENDB(BAS,$295,1)
        IF (NT.EQ.3) CALL DBFIND(17,1,FLD(NT),1,FL1(NT),1,CKT,
     1  1,3,1,NET)
        IF((NT.EQ.1).OR.(NT.EQ.2))CALL DBFIND(17,1,FLD(NT),1,
     1  FL1,1,CKT(1),1,3,1,NET)
        CALL DBNREC(NUMBER)
        IF (NUMBER.EQ.0) GOTO 280
        CALL DBCHNG(ATB,VALU)
        CALL DBCLOS
        TYPE 120
120     FORMAT('+','... CHANGE IS COMPLETE')
        RETURN

280     TYPE 285
285     FORMAT(3X,'NO RELATION RECORD EXISTS...',/)
        RETURN

295     TYPE 297,IERT,IERC
297     FORMAT(1X,'ERROR EQUALS...  IERT = ',I3,4X,'IERC = 'I3)
        RETURN

        END
        SUBROUTINE FPRUPD(SITC,SITP,NET,NOD1,SLOT,HST1,CIRCKT,
     1  TROUB1,TECH,CNAM,KHST,COV,PRO,STH,EHR,PORT,PROD,LOC,
     2  VER,T40,SRGN,HRGN,LIN1,SNAM,SDAT,INT,F1,RECORD,IPXNA,
     3  CRDNM,PRTNM)

        INTEGER SITC(4),SITP(4),NOD1,PRTNM,CRDNM,CIRCKT(4)
        INTEGER TROUB1(4),TECH(3),CNAM(3),KHST,COV,PRO,STH,EHR
        INTEGER PORT,IPXNA,LOC(4),VER,T40,SRGN,HRGN,LIN1(16)
        INTEGER SNAM(3),SDAT,INT,F1,RECORD,Z,SLOT,HST1,PROD,P
        INTEGER NATTN,ATTN,IERT,IERC,IBF
	COMMON /NATTN/NATTN
	COMMON /ATTN/ATTN(170)
	DOUBLE PRECISION NET,NETW
	COMMON /IBF/IBF,IERT,IERC

	CALL OPENDB(10,$999,1)
        CALL DBFIND(17,1,WELL,1,18,1,IPXNA,1,6,1,CRDNM,1,5,1,PRTNM)
        CALL DBNREC(RECORD)
        IF (RECORD.GT.0) GOTO 50
        Z=1
        CALL DBFIND(17,1,'Z')
        CALL DBGREC($999,1)
        GOTO 55

50      CALL DBGREC($999,1)
55      CALL DBVAL(1,SITC,2,SITP,3,NET,4,NOD1,5,SLOT,6,HST1,7,CIRCKT,
     1  8,TROUB1,9,TECH,10,CNAM,11,KHST,12,COV,13,PRO,14,STH,15,EHR,16,
     2  PORT,18,PROD,21,LOC,22,VER,23,T40,25,SRGN,26,HRGN,27,LIN1,
     3  28,SNAM,29,SDAT,30,INT,31,F1)
        CALL DBNDAT(SDAT,IM,ID,IY)
57      FORMAT(2A5)
        SLOT=PRTNM
        HST1=CRDNM
        PROD=IPXNA

        TYPE 60
60      FORMAT(' BEGIN CHECK FOR EMPTY FIELDS',/)
        CALL GTHR3('CUSTOMER NAME:  ',CNAM,Z,2)
        IF (LOC(1).EQ.' ') CALL GTWO('SITE LOCATION:  ',LOC,Z,2)
        IF (SITC(1).EQ.' ') CALL GTHRE('SITE CONTACT:  ',SITC,Z)
        IF (SITP(1).EQ.' ') CALL GTHRE('SITE PHONE #:  ',SITP,Z)
        IF (NOD1.EQ.0) CALL GTW3('FR NODE #:  ',NOD1,Z)
        IF (CIRCKT(1).EQ.' ') CALL GTWO('CIRCUIT #:  ',CIRCKT,Z,2)
        IF (TROUB1(1).EQ.' ') CALL GTHRE('IP ADDRESS:  ',TROUB1,Z)
        IF (KHST.EQ.0) CALL GONE('DLCI:  ',KHST,Z)
        IF (PRO.EQ.0) CALL BNDLD(PRO,Z)
        IF(TECH(1).EQ.' ') CALL GTHR3('COMM SPECIALIST:  ',TECH,Z,1)
        IF (SRGN.EQ.' ') CALL GRGN(1,P,Z)
        IF ((SRGN.EQ.' ').AND.(P.GT.0)) SRGN=ATTN(P)
        IF (HRGN.EQ.' ') CALL GRGN(2,P,Z)
        IF ((HRGN.EQ.' ').AND.(P.GT.0)) HRGN=ATTN(P)
        IF (F1.EQ.0) CALL GZONE(F1,Z)
        RETURN

999     TYPE 1000,IERT,IERC
1000    FORMAT(/1X,'ERROR TYPE = ',I3,4X,'ERROR CODE = ',I3,/)
        IF(CCC.EQ.0) CCC=1
        RETURN
        END
        SUBROUTINE BNDLD(IN,Z)
        INTEGER IN,Z

	TYPE 10
10	FORMAT('+BUNDLED ...1=NO, 2=YES : ',$)
	ACCEPT 20,IN
20	FORMAT(I8)
	IF (IN.GT.0) Z=2
	RETURN

        END

   S&c.Y